//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDF.PurchaseOrder {
    
    public partial class PurchaseOrder : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "PDF.PurchaseOrder.PurchaseOrder.vsrepx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.POTable = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("POTable");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.DueDateLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("DueDateLbl");
            this.PODueDateValueLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("PODueDateValueLbl");
            this.tableRow3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow3");
            this.tableRow9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow9");
            this.tableRow4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow4");
            this.tableRow5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow5");
            this.tableRow6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow6");
            this.DeliveryCostLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("DeliveryCostLbl");
            this.PODeliveryCostValueLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("PODeliveryCostValueLbl");
            this.discountlbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("discountlbl");
            this.PODiscountLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("PODiscountLbl");
            this.SubTotalbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("SubTotalbl");
            this.POSubTotalValueLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("POSubTotalValueLbl");
            this.VatLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("VatLbl");
            this.POVatValueLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("POVatValueLbl");
            this.TotalLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("TotalLbl");
            this.POTotalValueLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("POTotalValueLbl");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");
            this.tableCell3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell3");
            this.tableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell4");
            this.tableCell6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell6");
            this.QuoteNumberValueLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("QuoteNumberValueLbl");
            this.QuoteNumberLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("QuoteNumberLbl");
            this.pictureBox6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox6");
            this.POWorkLandlineNo1Lbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("POWorkLandlineNo1Lbl");
            this.label19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label19");
            this.label21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label21");
            this.label24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label24");
            this.pictureBox5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox5");
            this.POStreetAddress1Lbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("POStreetAddress1Lbl");
            this.POCity1Lbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("POCity1Lbl");
            this.label7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label7");
            this.pictureBox4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox4");
            this.label8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label8");
            this.label18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label18");
            this.label22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label22");
            this.label23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label23");
            this.label20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label20");
            this.label25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label25");
            this.pictureBox9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox9");
            this.label5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label5");
            this.label9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label9");
            this.POHeadingLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("POHeadingLbl");
            this.pictureBox3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox3");
            this.pictureBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox1");
            this.POSupplierSuburbLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("POSupplierSuburbLbl");
            this.SupplierLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("SupplierLbl");
            this.DeliveryToLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("DeliveryToLbl");
            this.PODateCreatedLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("PODateCreatedLbl");
            this.PODateCreatedValueLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("PODateCreatedValueLbl");
            this.POSupplierCompanyNameLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("POSupplierCompanyNameLbl");
            this.PONumberLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("PONumberLbl");
            this.POSupplierStreetAddressLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("POSupplierStreetAddressLbl");
            this.POSupplierCityLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("POSupplierCityLbl");
            this.POSupplierPostCodeLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("POSupplierPostCodeLbl");
            this.PONumberValueLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("PONumberValueLbl");
            this.customerTable = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("customerTable");
            this.pictureBox2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox2");
            this.customerTableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("customerTableRow1");
            this.customerNameRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("customerNameRow");
            this.customerContactNameRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("customerContactNameRow");
            this.tableRow7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow7");
            this.customerAddressRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("customerAddressRow");
            this.tableRow8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow8");
            this.customerCityRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("customerCityRow");
            this.PORequesterNameSurnameLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("PORequesterNameSurnameLbl");
            this.PORequesterCompanyNameLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("PORequesterCompanyNameLbl");
            this.PORequesterPlantLocationStreetAddressLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("PORequesterPlantLocationStreetAddressLbl");
            this.PORequesterSuburbLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("PORequesterSuburbLbl");
            this.PORequesterPlantLocationPhysicalCityLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("PORequesterPlantLocationPhysicalCityLbl");
            this.PORequesterPostCodeLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("PORequesterPostCodeLbl");
            this.PORequesterWorkLandlineNoLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("PORequesterWorkLandlineNoLbl");
            this.Panel = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("Panel");
            this.InstructLbl1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("InstructLbl1");
            this.InstructLbl4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("InstructLbl4");
            this.InstructLbl3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("InstructLbl3");
            this.InstructLbl2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("InstructLbl2");
            this.GradientFooterBackground = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("GradientFooterBackground");
            this.Companylbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Companylbl");
            this.companyNamelbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("companyNamelbl");

            // Styles
            this.baseControlStyle = reportInitializer.GetStyle("baseControlStyle");
            this.Style1 = reportInitializer.GetStyle("Style1");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTable POTable;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell DueDateLbl;
        private DevExpress.XtraReports.UI.XRTableCell PODueDateValueLbl;
        private DevExpress.XtraReports.UI.XRTableRow tableRow3;
        private DevExpress.XtraReports.UI.XRTableRow tableRow9;
        private DevExpress.XtraReports.UI.XRTableRow tableRow4;
        private DevExpress.XtraReports.UI.XRTableRow tableRow5;
        private DevExpress.XtraReports.UI.XRTableRow tableRow6;
        private DevExpress.XtraReports.UI.XRTableCell DeliveryCostLbl;
        private DevExpress.XtraReports.UI.XRTableCell PODeliveryCostValueLbl;
        private DevExpress.XtraReports.UI.XRTableCell discountlbl;
        private DevExpress.XtraReports.UI.XRTableCell PODiscountLbl;
        private DevExpress.XtraReports.UI.XRTableCell SubTotalbl;
        private DevExpress.XtraReports.UI.XRTableCell POSubTotalValueLbl;
        private DevExpress.XtraReports.UI.XRTableCell VatLbl;
        private DevExpress.XtraReports.UI.XRTableCell POVatValueLbl;
        private DevExpress.XtraReports.UI.XRTableCell TotalLbl;
        private DevExpress.XtraReports.UI.XRTableCell POTotalValueLbl;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell3;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell6;
        private DevExpress.XtraReports.UI.XRLabel QuoteNumberValueLbl;
        private DevExpress.XtraReports.UI.XRLabel QuoteNumberLbl;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox6;
        private DevExpress.XtraReports.UI.XRLabel POWorkLandlineNo1Lbl;
        private DevExpress.XtraReports.UI.XRLabel label19;
        private DevExpress.XtraReports.UI.XRLabel label21;
        private DevExpress.XtraReports.UI.XRLabel label24;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox5;
        private DevExpress.XtraReports.UI.XRLabel POStreetAddress1Lbl;
        private DevExpress.XtraReports.UI.XRLabel POCity1Lbl;
        private DevExpress.XtraReports.UI.XRLabel label7;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox4;
        private DevExpress.XtraReports.UI.XRLabel label8;
        private DevExpress.XtraReports.UI.XRLabel label18;
        private DevExpress.XtraReports.UI.XRLabel label22;
        private DevExpress.XtraReports.UI.XRLabel label23;
        private DevExpress.XtraReports.UI.XRLabel label20;
        private DevExpress.XtraReports.UI.XRLabel label25;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox9;
        private DevExpress.XtraReports.UI.XRLabel label5;
        private DevExpress.XtraReports.UI.XRLabel label9;
        private DevExpress.XtraReports.UI.XRLabel POHeadingLbl;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox3;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox1;
        private DevExpress.XtraReports.UI.XRLabel POSupplierSuburbLbl;
        private DevExpress.XtraReports.UI.XRLabel SupplierLbl;
        private DevExpress.XtraReports.UI.XRLabel DeliveryToLbl;
        private DevExpress.XtraReports.UI.XRLabel PODateCreatedLbl;
        private DevExpress.XtraReports.UI.XRLabel PODateCreatedValueLbl;
        private DevExpress.XtraReports.UI.XRLabel POSupplierCompanyNameLbl;
        private DevExpress.XtraReports.UI.XRLabel PONumberLbl;
        private DevExpress.XtraReports.UI.XRLabel POSupplierStreetAddressLbl;
        private DevExpress.XtraReports.UI.XRLabel POSupplierCityLbl;
        private DevExpress.XtraReports.UI.XRLabel POSupplierPostCodeLbl;
        private DevExpress.XtraReports.UI.XRLabel PONumberValueLbl;
        private DevExpress.XtraReports.UI.XRTable customerTable;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox2;
        private DevExpress.XtraReports.UI.XRTableRow customerTableRow1;
        private DevExpress.XtraReports.UI.XRTableRow customerNameRow;
        private DevExpress.XtraReports.UI.XRTableRow customerContactNameRow;
        private DevExpress.XtraReports.UI.XRTableRow tableRow7;
        private DevExpress.XtraReports.UI.XRTableRow customerAddressRow;
        private DevExpress.XtraReports.UI.XRTableRow tableRow8;
        private DevExpress.XtraReports.UI.XRTableRow customerCityRow;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterNameSurnameLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterCompanyNameLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterPlantLocationStreetAddressLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterSuburbLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterPlantLocationPhysicalCityLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterPostCodeLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterWorkLandlineNoLbl;
        private DevExpress.XtraReports.UI.XRPanel Panel;
        private DevExpress.XtraReports.UI.XRLabel InstructLbl1;
        private DevExpress.XtraReports.UI.XRLabel InstructLbl4;
        private DevExpress.XtraReports.UI.XRLabel InstructLbl3;
        private DevExpress.XtraReports.UI.XRLabel InstructLbl2;
        private DevExpress.XtraReports.UI.XRPictureBox GradientFooterBackground;
        private DevExpress.XtraReports.UI.XRControlStyle baseControlStyle;
        private DevExpress.XtraReports.UI.XRControlStyle Style1;
        private DevExpress.XtraReports.UI.XRLabel Companylbl;
        private DevExpress.XtraReports.UI.XRLabel companyNamelbl;
    }
}
