//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDF.BarcodePDF {
    
    public partial class BarcodePDF : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "PDF.BarcodePDF.BarcodePDF.vsrepx");

            // Controls
         
            this.InstructLbl1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("InstructLbl1");
            this.InstructLbl4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("InstructLbl4");
            this.InstructLbl3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("InstructLbl3");
            this.InstructLbl2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("InstructLbl2");
            // Styles
            this.baseControlStyle = reportInitializer.GetStyle("baseControlStyle");
            this.Style1 = reportInitializer.GetStyle("Style1");
        }

        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTable POTable;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell DueDateLbl;
        private DevExpress.XtraReports.UI.XRTableCell PODueDateValueLbl;
        private DevExpress.XtraReports.UI.XRTableRow tableRow3;
        private DevExpress.XtraReports.UI.XRTableRow tableRow9;
        private DevExpress.XtraReports.UI.XRTableRow tableRow4;
        private DevExpress.XtraReports.UI.XRTableRow tableRow5;
        private DevExpress.XtraReports.UI.XRTableRow tableRow6;
        private DevExpress.XtraReports.UI.XRTableCell DeliveryCostLbl;
        private DevExpress.XtraReports.UI.XRTableCell PODeliveryCostValueLbl;
        private DevExpress.XtraReports.UI.XRTableCell discountlbl;
        private DevExpress.XtraReports.UI.XRTableCell PODiscountLbl;
        private DevExpress.XtraReports.UI.XRTableCell SubTotalbl;
        private DevExpress.XtraReports.UI.XRTableCell POSubTotalValueLbl;
        private DevExpress.XtraReports.UI.XRTableCell VatLbl;
        private DevExpress.XtraReports.UI.XRTableCell POVatValueLbl;
        private DevExpress.XtraReports.UI.XRTableCell TotalLbl;
        private DevExpress.XtraReports.UI.XRTableCell POTotalValueLbl;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell3;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell6;
        private DevExpress.XtraReports.UI.XRLabel POHeadingLbl;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox1;
        private DevExpress.XtraReports.UI.XRLabel POSupplierSuburbLbl;
        private DevExpress.XtraReports.UI.XRLabel SupplierLbl;
        private DevExpress.XtraReports.UI.XRLabel POWorkLandlineNo1Lbl;
        private DevExpress.XtraReports.UI.XRLabel POStreetAddress1Lbl;
        private DevExpress.XtraReports.UI.XRLabel POCity1Lbl;
        private DevExpress.XtraReports.UI.XRLabel DeliveryToLbl;
        private DevExpress.XtraReports.UI.XRLabel PODateCreatedLbl;
        private DevExpress.XtraReports.UI.XRLabel PODateCreatedValueLbl;
        private DevExpress.XtraReports.UI.XRLabel POSupplierCompanyNameLbl;
        private DevExpress.XtraReports.UI.XRLabel PONumberLbl;
        private DevExpress.XtraReports.UI.XRLabel POSupplierStreetAddressLbl;
        private DevExpress.XtraReports.UI.XRLabel POSupplierCityLbl;
        private DevExpress.XtraReports.UI.XRLabel POSupplierPostCodeLbl;
        private DevExpress.XtraReports.UI.XRLabel PONumberValueLbl;
        private DevExpress.XtraReports.UI.XRTable customerTable;
        private DevExpress.XtraReports.UI.XRPictureBox GradientHeaderBackground;
        private DevExpress.XtraReports.UI.XRTableRow customerTableRow1;
        private DevExpress.XtraReports.UI.XRTableRow customerNameRow;
        private DevExpress.XtraReports.UI.XRTableRow customerContactNameRow;
        private DevExpress.XtraReports.UI.XRTableRow tableRow7;
        private DevExpress.XtraReports.UI.XRTableRow customerAddressRow;
        private DevExpress.XtraReports.UI.XRTableRow tableRow8;
        private DevExpress.XtraReports.UI.XRTableRow customerCityRow;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterNameSurnameLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterCompanyNameLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterPlantLocationStreetAddressLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterSuburbLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterPlantLocationPhysicalCityLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterPostCodeLbl;
        private DevExpress.XtraReports.UI.XRTableCell PORequesterWorkLandlineNoLbl;
        private DevExpress.XtraReports.UI.XRPanel Panel;
        private DevExpress.XtraReports.UI.XRLabel InstructLbl1;
        private DevExpress.XtraReports.UI.XRLabel InstructLbl4;
        private DevExpress.XtraReports.UI.XRLabel InstructLbl3;
        private DevExpress.XtraReports.UI.XRLabel InstructLbl2;
        private DevExpress.XtraReports.UI.XRPictureBox GradientFooterBackground;
        private DevExpress.XtraReports.UI.XRControlStyle baseControlStyle;
        private DevExpress.XtraReports.UI.XRControlStyle Style1;
    }
}
